### ISSUE TITLE
original data 3d how to apply and best model checkpoint to reproduce the results

### ISSUE THREAD

**Issue by saisusmitha** [JuliaWolleb/Diffusion-based-Segmentation#28]
Your data folder contains less 2D data( small set) but the original data(https://www.med.upenn.edu/cbica/brats2020/data.html) is 3d( lots of folders) so did you include how to run the complete original 3D data as I couldn't find it in the codes? also, can you kindly share the trained model checkpoint through which you got the published results?

**Comment by saisusmitha** [comment]
@JuliaWolleb kindly answer this

**Comment by JuliaWolleb** [comment]
Please read our paper:
"We slice the 3D MR scans in axial slices. Since tumors rarely occur on the upper or lower
part of the brain, we exclude the lowest 80 slices and the uppermost 26 slices. For intensity
normalization, we cut the top and bottom one percentile of the pixel intensities. We crop
the images to a size of (4, 224, 224). The provided ground truth labels contain four classes,
which are background, GD-enhancing tumor, the peritumoral edema, and the necrotic and
non-enhancing tumor core. We merge the three different tumor classes into one class and
therefore define the segmentation problem as a pixel-wise binary classification. No data
augmentation is applied."
Store these 2D slices as suggested in the mini-example in the folder _/data_.
