### ISSUE TITLE
Training---socket.gaierror: [Errno 11001] getaddrinfo failed-hostname = socket.gethostbyname(socket.getfqdn())

### ISSUE THREAD

**Issue by yug125lk** [JuliaWolleb/Diffusion-based-Segmentation#55]
Hi, thank you again for sharing this code. I use only a single GPU, so I changed the node to 1 (it works with a CPU but not with a GPU). I got this error.
GPUS_PER_NODE = 1
SETUP_RETRY_COUNT = 3

python version 3.8
torch 1.9.0+cu111
torchvision 0.10.0+cu111
Windows

  File "scripts/segmentation_train.py", line 89, in <module>
    main()
  File "scripts/segmentation_train.py", line 25, in main
    dist_util.setup_dist()
  File ".\guided_diffusion\dist_util.py", line 34, in setup_dist
    hostname = socket.gethostbyname(socket.getfqdn())
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by JuliaWolleb** [comment]
Hi
I am not sure the problem is GPUS_PER_NODE, since (in the version you get in this repo) we do not use MPI (please check out the[ original repo from openai](https://github.com/openai/guided-diffusion/blob/main/guided_diffusion/dist_util.py), where they use mpi4py).
Rather check whether `th.cuda.is_available()`, since the error occurs in[ this line.](https://github.com/JuliaWolleb/Diffusion-based-Segmentation/blob/676f214035e90edd0357f51feab45841e4aefcfb/guided_diffusion/dist_util.py#L29C29-L29C51)

**Comment by yug125lk** [comment]
It works. Thank you for your reply.
