### ISSUE TITLE
run_step and out_channels problems

### ISSUE THREAD

**Issue by Rengongzhineng1999zxwang** [JuliaWolleb/Diffusion-based-Segmentation#7]
1.  There are two **self.run_step(batch, cond)**  within run_loop in guided_diffusion/train_util.py, is it right? One run_step(batch, cond) might be ok?

> def run_loop(self):
>             ......
>             ......
>             self.run_step(batch, cond)
>             sample = self.run_step(batch, cond)
>             i += 1
>             ......
>             ......

2.  I don't understand the **out_channels=2 in UNetModel**. Maybe out_channels=1 is better? because it's the binary image

Thank u for your help

**Comment by JuliaWolleb** [comment]
1. You are right, this mistake is already corrected in the current commit.
2. This depends on your flags. if you set the flag `--learn_sigma True`, then your out_channels=2*in_channels. This is because you need to learn the mean and the variance. If your set `--learn_sigma False`, then you only learn the mean, and out_channels=in_channels.

**Comment by Rengongzhineng1999zxwang** [comment]
All right. I need to set out_channels as 1 in guided_diffusion/script_util.py when learn_sigma is False, is itright?

> return UNetModel(
>         image_size=image_size,
>         in_channels=5,
>         model_channels=num_channels,
>         out_channels=2
>          ....
>     )

**Comment by JuliaWolleb** [comment]
yes, that should work

**Comment by Rengongzhineng1999zxwang** [comment]
all right. thank you
